import Head from "next/head";
import { FilmDetail } from "@/components/FilmDetail";
import { GetServerSideProps } from "next";
import { searchFilm } from "@/service/FilmService";
import { useEffect } from "react";

interface Props {
  film: FilmMetaData;
}

export default function Film({ film }: Props) {
  return (
    <>
      <Head>
        <title>SuperaFlix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FilmDetail film={film} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { slug } = context.params!;

  try {
    const { data } = await searchFilm(slug as string);

    console.log(data);

    if (data.Error) {
      return {
        notFound: true,
      };
    }

    return {
      props: {
        film: data,
      },
    };
  } catch (error) {
    console.log("erro:", error);
    return {
      props: {
        post: null,
      },
    };
  }
};
