import { FileDropzone } from "@/components/FileDropzone";
import { UploadData } from "@/components/UploadData";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>SuperaFlix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <UploadData />
    </>
  );
}
